apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: algorithm-sample
spec:
  template:
    metadata:
      labels:
        app: alg-with-storage
    spec:
      volumes:
        - name: storage-credentials
          secret:
            secretName: storage-auth-credentials
      containers:
      - name: "algorithm-sample-main"
        image: "gcr.io/dulcet-coast-134823/alg:build-9"
        imagePullPolicy: Always
        command: ['sh', '-c', 'bash /src/setup.sh']
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
            #postStart:
            #  exec:
            #    command: ["gcsfuse", "-o", "nonempty", "$FUSE_BUCKET_NAME", "$FUSE_MOUNT_DIR"]
            preStop:
              exec:
                command: ["fusermount", "-u", "$FUSE_MOUNT_DIR"]
        env:
          - name: FUSE_MOUNT_DIR
            value: "/src/storage"
          - name: FUSE_BUCKET_NAME
            value: "cloud-connector-app"
          - name: ALG_DATA_DIR
            value: "/src/storage/.shared"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/auth/app-storage-credentials.json"
        volumeMounts:
          - name: storage-credentials
            mountPath: /auth
            readOnly: true
      # volumes:
      #   - name: storage-credentials
      #     secret:
      #       secretName: storage-auth-credentials
      #       items:
      #         - key: credentials
      #           path: storage-credentials.json     